org.gradle.daemon=false
org.gradle.jvmargs=-Xmx6500m
minecraft_version=1.21.1
mod_id=lootrmon
mod_version=0.0.0.1
maven_group=noobanidus.mods.lootremon

fabric_loader_version=0.17.3
fabric_api_version=0.116.7+1.21.1
lootr_version=1.21-1.10.35.97

neoforge_version=21.1.214
kotlin_fabric_version=1.13.7+kotlin.2.2.21
kotlin_neo_version=5.10.0

cobblemon_version=1.7.1+1.21.1
accessories_version=1.1.0-beta.52+1.21.1

# Libraries
mixin_extras=0.5.0
auto_service_version=1.0.1

# Compat Dependencies
mod_menu=11.0.0
jei_mc=1.21
jei=19.5.0.35
rei=16.0.729
cloth_config=15.0.127
emi=1.1.10+1.21
architectury=13.0.8

git_previous_commit=e81af40453234a40ffd42ea50cfa907febf4b456
